foreground         #c3c3c5
background         #0f1017
background_opacity 1.0
cursor             #c3c3c5

active_tab_foreground     #0f1017
active_tab_background     #c3c3c5
inactive_tab_foreground   #c3c3c5
inactive_tab_background   #0f1017

active_border_color   #c3c3c5
inactive_border_color #0f1017
bell_border_color     #C6657C

color0       #0f1017
color8       #5b5b6f
color1       #C6657C
color9       #C6657C
color2       #999270
color10      #999270
color3       #737E85
color11      #737E85
color4       #99989B
color12      #99989B
color5       #B7ABAF
color13      #B7ABAF
color6       #CAAE99
color14      #CAAE99
color7       #c3c3c5
color15      #c3c3c5
