#     _  _   __   __ _  __  ____  __  ____  ____
#    ( \/ ) /  \ (  ( \(  )(_  _)/  \(  _ \/ ___)
#    / \/ \(  O )/    / )(   )( (  O ))   /\___ \
#    \_)(_/ \__/ \_)__)(__) (__) \__/(__\_)(____/


# See https://wiki.hypr.land/Configuring/Monitors/
monitor= , 1920x1080@60, auto, 1
