[config]

[config.wallpaper]
set = true
command = "hyprctl hyprpaper wallpaper  , {{ image }}"


# GTK 3 Applications
[templates.gtk3]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-gtk3.css"
output_path = "~/.dotfiles/.config/gtk-3.0/gtk.css"

# GTK 4 Applications
[templates.gtk4]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-gtk4.css"
output_path = "~/.dotfiles/.config/gtk-4.0/gtk.css"

# Ghostty Terminal
[templates.ghostty]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-ghostty.ghostty"
output_path = "~/.dotfiles/.config/ghostty/themes/Matugen"
post_hook = 'pkill -SIGUSR2 ghostty'

# Zed Editor
[templates.zed]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-zed.json"
output_path = "~/.dotfiles/.config/zed/themes/matugen.json"
post_hook = 'pkill -SIGUSR2 zeditor'

# Btop
[templates.btop]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-btop.theme"
output_path = "~/.dotfiles/.config/btop/themes/matugen.theme"

# Telegram Desktop
[templates.telegram]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-telegram.tdesktop-theme"
output_path = "~/.dotfiles/.config/matugen/output/telegram.tdesktop-theme"

# Visual studio code
[templates.vscode-insiders]
input_path = "~/.dotfiles/.config/matugen/configuration/matugen-vscode.json"
output_path = "~/.vscode-insiders/extensions/noctalia.noctaliatheme-0.0.5/themes/NoctaliaTheme-color-theme.json"
