$image = /home/sainbiswas/.dotfiles/wallpapers/may_waterfall.png


$background = rgba(0c1516ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(293233ff)

$inverse_primary = rgba(845401ff)

$inverse_surface = rgba(dae4e5ff)

$on_background = rgba(dae4e5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(462a00ff)

$on_primary_container = rgba(ffddb6ff)

$on_primary_fixed = rgba(2a1800ff)

$on_primary_fixed_variant = rgba(643f00ff)

$on_secondary = rgba(2b2e4dff)

$on_secondary_container = rgba(e0e0ffff)

$on_secondary_fixed = rgba(161937ff)

$on_secondary_fixed_variant = rgba(414465ff)

$on_surface = rgba(dae4e5ff)

$on_surface_variant = rgba(b8caccff)

$on_tertiary = rgba(00363bff)

$on_tertiary_container = rgba(a8eef7ff)

$on_tertiary_fixed = rgba(001f23ff)

$on_tertiary_fixed_variant = rgba(004f56ff)

$outline = rgba(839496ff)

$outline_variant = rgba(394a4cff)

$primary = rgba(fbba65ff)

$primary_container = rgba(643f00ff)

$primary_fixed = rgba(ffddb6ff)

$primary_fixed_dim = rgba(fbba65ff)

$scrim = rgba(000000ff)

$secondary = rgba(c2c4ebff)

$secondary_container = rgba(414465ff)

$secondary_fixed = rgba(e0e0ffff)

$secondary_fixed_dim = rgba(c2c4ebff)

$shadow = rgba(000000ff)

$source_color = rgba(0c4744ff)

$surface = rgba(0c1516ff)

$surface_bright = rgba(323b3cff)

$surface_container = rgba(182122ff)

$surface_container_high = rgba(222c2dff)

$surface_container_highest = rgba(2d3638ff)

$surface_container_low = rgba(141d1eff)

$surface_container_lowest = rgba(071011ff)

$surface_dim = rgba(0c1516ff)

$surface_tint = rgba(fbba65ff)

$surface_variant = rgba(394a4cff)

$tertiary = rgba(8dd2dbff)

$tertiary_container = rgba(004f56ff)

$tertiary_fixed = rgba(a8eef7ff)

$tertiary_fixed_dim = rgba(8dd2dbff)

