$image = /home/sainbiswas/.dotfiles/wallpapers/genshin-skirk.jpg


$background = rgba(12131aff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2f3038ff)

$inverse_primary = rgba(386933ff)

$inverse_surface = rgba(e3e1ecff)

$on_background = rgba(e3e1ecff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(053908ff)

$on_primary_container = rgba(b9f1acff)

$on_primary_fixed = rgba(002202ff)

$on_primary_fixed_variant = rgba(20511dff)

$on_secondary = rgba(492535ff)

$on_secondary_container = rgba(ffd8e6ff)

$on_secondary_fixed = rgba(301120ff)

$on_secondary_fixed_variant = rgba(623b4cff)

$on_surface = rgba(e3e1ecff)

$on_surface_variant = rgba(c5c5d6ff)

$on_tertiary = rgba(252d5aff)

$on_tertiary_container = rgba(dee0ffff)

$on_tertiary_fixed = rgba(0f1744ff)

$on_tertiary_fixed_variant = rgba(3c4372ff)

$outline = rgba(8f8f9fff)

$outline_variant = rgba(444654ff)

$primary = rgba(9ed592ff)

$primary_container = rgba(20511dff)

$primary_fixed = rgba(b9f1acff)

$primary_fixed_dim = rgba(9ed592ff)

$scrim = rgba(000000ff)

$secondary = rgba(edb8ccff)

$secondary_container = rgba(623b4cff)

$secondary_fixed = rgba(ffd8e6ff)

$secondary_fixed_dim = rgba(edb8ccff)

$shadow = rgba(000000ff)

$source_color = rgba(edeffaff)

$surface = rgba(12131aff)

$surface_bright = rgba(383941ff)

$surface_container = rgba(1e1f27ff)

$surface_container_high = rgba(292931ff)

$surface_container_highest = rgba(34343cff)

$surface_container_low = rgba(1a1b23ff)

$surface_container_lowest = rgba(0d0e15ff)

$surface_dim = rgba(12131aff)

$surface_tint = rgba(9ed592ff)

$surface_variant = rgba(444654ff)

$tertiary = rgba(bcc3faff)

$tertiary_container = rgba(3c4372ff)

$tertiary_fixed = rgba(dee0ffff)

$tertiary_fixed_dim = rgba(bcc3faff)

