# MONITORS
monitor=,preferred,auto,1

# MY PROGRAMS
$terminal = kitty
$fileManager = nautilus

$confs = ~/.dotfiles/.config/hypr/configurations


source = $confs/autostart.conf       # AUTOSTART
source = $confs/env.conf             # ENVIRONMENT VARIABLES
source = $confs/visuals.conf         # LOOK AND FEEL
source = $confs/inputs.conf          # INPUT
source = $confs/keybindings.conf     # KEYBINDINGS
source = $confs/windowrules.conf     # WINDOWS AND WORKSPACES
