[colors.primary]
background = '#12131a'
foreground = '#e3e1ec'

[colors.cursor]
text = '#e3e1ec'
cursor = '#c5c5d6'

[colors.vi_mode_cursor]
text = '#12131a'
cursor = '#9ed592'

[colors.search.matches]
foreground = '#444654'
background = '#bcc3fa'

[colors.search.focused_match]
foreground = '#444654'
background = '#9ed592'

[colors.footer_bar]
foreground = '#444654'
background = '#e3e1ec'

[colors.hints.start]
foreground = '#444654'
background = '#edb8cc'

[colors.hints.end]
foreground = '#444654'
background = '#edb8cc'

[colors.selection]
text = '#12131a'
background = '#9ed592'


[colors.normal]
black = "#12131a"
red = "#ffb4ab"
green = "#9ed592"
yellow = "#edb8cc"
blue = "#bcc3fa"
magenta = "#93000a"
cyan = "#b9f1ac"
white = "#c5c5d6"


[colors.bright]
black = "#383941"
red = "#ffb4ab"
green = "#9ed592"
yellow = "#edb8cc"
blue = "#bcc3fa"
magenta = "#93000a"
cyan = "#b9f1ac"
white = "#e3e1ec"
