[general]
import = ["~/.dotfiles/.config/alacritty/themes/rose-pine.toml"]

[font]
normal = { family = "DankMono Nerd Font", style = "Regular" }
bold = { family = "DankMono Nerd Font", style = "Bold" }
italic = { family = "DankMono Nerd Font", style = "Italic" }
bold_italic = { family = "DankMono Nerd Font", style = "Bold Italic" }
size = 16

[cursor.style]
shape = "Beam"
blinking = "Off"

[window]
decorations = "none"
opacity = 0.80
dynamic_padding = true
decorations_theme_variant = "dark"

[window.padding]
x = 10
y = 10
